/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package labpractico5;

import java.util.TreeMap;
import java.util.ArrayList;
import java.util.Set;
import javax.swing.JInternalFrame;
/**
 *
 * @author patri
 */
public class frmMenuPrincipal extends javax.swing.JFrame {
      
     static TreeMap<String,DirectorioTelefonico> directorioPrincipal; 
     static ArrayList<String> ciudades ;
     static DirectorioTelefonico direct;
     static Set<Long> telefonos;
    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal() {
        initComponents();
        ciudades = new ArrayList<String>();
        directorioPrincipal = new TreeMap<>();
        direct = new DirectorioTelefonico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuClientes = new javax.swing.JMenu();
        menuAgregarCliente = new javax.swing.JMenuItem();
        menuBuscarCliente = new javax.swing.JMenuItem();
        menuBorrarCliente = new javax.swing.JMenuItem();
        menuDirectorio = new javax.swing.JMenu();
        menuBuscarCiudad = new javax.swing.JMenuItem();
        menuBuscarApellido = new javax.swing.JMenuItem();
        menuCiudades = new javax.swing.JMenu();
        menuAgregarCiudad = new javax.swing.JMenuItem();
        menuOut = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );

        menuClientes.setBackground(new java.awt.Color(0, 0, 0));
        menuClientes.setText("Clientes");

        menuAgregarCliente.setBackground(new java.awt.Color(204, 204, 204));
        menuAgregarCliente.setText("Agregar Cliente");
        menuAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgregarClienteActionPerformed(evt);
            }
        });
        menuClientes.add(menuAgregarCliente);

        menuBuscarCliente.setText("Buscar Cliente");
        menuBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscarClienteActionPerformed(evt);
            }
        });
        menuClientes.add(menuBuscarCliente);

        menuBorrarCliente.setText("Borrar Cliente");
        menuBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBorrarClienteActionPerformed(evt);
            }
        });
        menuClientes.add(menuBorrarCliente);

        jMenuBar1.add(menuClientes);

        menuDirectorio.setBackground(new java.awt.Color(204, 204, 204));
        menuDirectorio.setForeground(new java.awt.Color(0, 0, 0));
        menuDirectorio.setText("Directorio");

        menuBuscarCiudad.setText("Buscar Cliente por ciudad");
        menuBuscarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscarCiudadActionPerformed(evt);
            }
        });
        menuDirectorio.add(menuBuscarCiudad);

        menuBuscarApellido.setText("Buscar telefono por apellido");
        menuBuscarApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscarApellidoActionPerformed(evt);
            }
        });
        menuDirectorio.add(menuBuscarApellido);

        jMenuBar1.add(menuDirectorio);

        menuCiudades.setBackground(new java.awt.Color(204, 204, 204));
        menuCiudades.setForeground(new java.awt.Color(0, 0, 0));
        menuCiudades.setText("Ciudades");

        menuAgregarCiudad.setText("Agregar Ciudad");
        menuAgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgregarCiudadActionPerformed(evt);
            }
        });
        menuCiudades.add(menuAgregarCiudad);

        jMenuBar1.add(menuCiudades);

        menuOut.setBackground(new java.awt.Color(204, 204, 204));
        menuOut.setForeground(new java.awt.Color(0, 0, 0));
        menuOut.setText("Salir");

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuOut.add(menuSalir);

        jMenuBar1.add(menuOut);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgregarClienteActionPerformed
        ventAgregarCliente ventanaCliente = new ventAgregarCliente();
        escritorio.add(ventanaCliente);
        ventanaCliente.setVisible(true);
        centrarInternalFrame(ventanaCliente);
    }//GEN-LAST:event_menuAgregarClienteActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
       int opcion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que querés Salir?",
                "Confirmar Salida",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE
        );
        
        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
            
            this.dispose();
                    
        }
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuAgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgregarCiudadActionPerformed
        ventAgregarCiudad ventanaCiudad = new ventAgregarCiudad();
        escritorio.add(ventanaCiudad);
        ventanaCiudad.setVisible(true);
        centrarInternalFrame(ventanaCiudad);
    }//GEN-LAST:event_menuAgregarCiudadActionPerformed

    private void menuBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarClienteActionPerformed
        ventanaBuscarCliente ventanBuscarC = new ventanaBuscarCliente();
        escritorio.add(ventanBuscarC);
        ventanBuscarC.setVisible(true);
        centrarInternalFrame(ventanBuscarC);
    }//GEN-LAST:event_menuBuscarClienteActionPerformed

    private void menuBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBorrarClienteActionPerformed
        VentanaBorrarCliente ventanaBorrar = new VentanaBorrarCliente();
        escritorio.add(ventanaBorrar);
        ventanaBorrar.setVisible(true);
        centrarInternalFrame(ventanaBorrar);
    }//GEN-LAST:event_menuBorrarClienteActionPerformed

    private void menuBuscarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarCiudadActionPerformed
        VentanaBuscarCiudad ventanaBuscarCiudad= new VentanaBuscarCiudad();
        escritorio.add(ventanaBuscarCiudad);
        ventanaBuscarCiudad.setVisible(true);
        centrarInternalFrame(ventanaBuscarCiudad);
        
    }//GEN-LAST:event_menuBuscarCiudadActionPerformed

    private void menuBuscarApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarApellidoActionPerformed
        ventBuscarPorApellido ventanaApellido = new ventBuscarPorApellido();
        escritorio.add(ventanaApellido);
        ventanaApellido.setVisible(true);
        centrarInternalFrame(ventanaApellido);
    }//GEN-LAST:event_menuBuscarApellidoActionPerformed

    private void centrarInternalFrame(JInternalFrame internalFrame) {
        // Centrar el internal frame en el escritorio
        int x = (escritorio.getWidth() - internalFrame.getWidth()) / 2;
        int y = (escritorio.getHeight() - internalFrame.getHeight()) / 2;
        internalFrame.setLocation(x, y);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuAgregarCiudad;
    private javax.swing.JMenuItem menuAgregarCliente;
    private javax.swing.JMenuItem menuBorrarCliente;
    private javax.swing.JMenuItem menuBuscarApellido;
    private javax.swing.JMenuItem menuBuscarCiudad;
    private javax.swing.JMenuItem menuBuscarCliente;
    private javax.swing.JMenu menuCiudades;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuDirectorio;
    private javax.swing.JMenu menuOut;
    private javax.swing.JMenuItem menuSalir;
    // End of variables declaration//GEN-END:variables
}
