/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package labpractico5;

import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leandro
 */
public class ventBuscarPorApellido extends javax.swing.JInternalFrame {
    
    private DefaultListModel<String> modeloListaAp = new DefaultListModel();
    private DefaultTableModel modelTabla = new DefaultTableModel();
    public boolean isCellEditable(int row, int column) {
        return false;
    }
    /**
     * Creates new form ventBuscarPorApellido
     */
    public ventBuscarPorApellido() {
        initComponents();
        armarCabecera();
        listaAp.setModel(modeloListaAp);
        llenarListaAp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaAp = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        txtApellidoBusca = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Buscar Cliente por Apellido");

        listaAp.setModel(modeloListaAp);
        listaAp.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaAp.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaApValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaAp);

        jLabel3.setText("Apellido:");

        txtApellidoBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoBuscaKeyTyped(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaClientes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtApellidoBusca))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(297, 297, 297))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtApellidoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnSalir))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void armarCabecera() {
        modelTabla.addColumn("DNI");
        modelTabla.addColumn("Nombre");
        modelTabla.addColumn("Apellido");
        modelTabla.addColumn("Direccion");
        modelTabla.addColumn("Ciudad");
        modelTabla.addColumn("Telefono");
        tablaClientes.setModel(modelTabla);
    }
    
    private void cargarTelefonosPorTxt() {
        limpiarTabla();
        String apellido = txtApellidoBusca.getText();
        for (Map.Entry<String, DirectorioTelefonico> aux : frmMenuPrincipal.directorioPrincipal.entrySet()) {
            DirectorioTelefonico directorio = aux.getValue();

            for (Map.Entry<Long, Cliente> aux2 : directorio.getDirectorio().entrySet()) {
                Cliente buscado = aux2.getValue();
                if (buscado.getApellido().equalsIgnoreCase(apellido)) {

                    String[] fila = {
                        buscado.getApellido(),
                        buscado.getNombre(),
                        buscado.getDomicilio(),
                        aux.getKey(),
                        aux2.getKey().toString()
                    };

                    modelTabla.addRow(fila);

                }
            }
        }
    }
    
    private void cargarTelefonosPorApellido() {
        limpiarTabla();
        String apellido = listaAp.getSelectedValue();
        for (Map.Entry<String, DirectorioTelefonico> aux : frmMenuPrincipal.directorioPrincipal.entrySet()) {
         DirectorioTelefonico directorio = aux.getValue();

         for (Map.Entry<Long, Cliente> aux2 : directorio.getDirectorio().entrySet()) {
             Cliente buscado = aux2.getValue();
             if (buscado.getApellido().equalsIgnoreCase(apellido)) {

                 String[] fila = {
                     buscado.getApellido(),
                     buscado.getNombre(),
                     buscado.getDomicilio(),
                     aux.getKey(),
                     aux2.getKey().toString()
                 };
                 
                 modelTabla.addRow(fila);

             }
         }
     } 
    }
  
    public void llenarListaAp() {
        
        modeloListaAp.clear(); 

        for (Map.Entry<String, DirectorioTelefonico> aux : frmMenuPrincipal.directorioPrincipal.entrySet()) {
            DirectorioTelefonico directorio = aux.getValue();
            for (Map.Entry<Long, Cliente> aux2 : directorio.getDirectorio().entrySet()) {
                String apellido = String.valueOf(aux2.getValue().getApellido());
                modeloListaAp.addElement(apellido);
            }
        }
    }
    
    private void limpiarTabla() {
        modelTabla.setRowCount(0);
    }
    
    private void configurarBusqueda() {
    
    txtApellidoBusca.getDocument().addDocumentListener(new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            buscarAlEscribir();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            buscarAlEscribir();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            buscarAlEscribir();
        }
    });
}

    private void buscarAlEscribir() {
        configurarBusqueda();
        String textoBusqueda = txtApellidoBusca.getText().trim();

        if (textoBusqueda.isEmpty()) {
            txtApellidoBusca.setText("");
            return;
        } else {
            cargarTelefonosPorTxt();
        }
    }
    private void listaApValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaApValueChanged
        listaAp.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    cargarTelefonosPorApellido();
                }
            }
        });
    }//GEN-LAST:event_listaApValueChanged

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtApellidoBuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoBuscaKeyTyped
        buscarAlEscribir();
    }//GEN-LAST:event_txtApellidoBuscaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listaAp;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTextField txtApellidoBusca;
    // End of variables declaration//GEN-END:variables
}
